apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
    <head><title>App 1</title></head>
    <body>
      <h1>Hello from the Kubernetes App!</h1>
      <p>This content is served from a ConfigMap mounted as a volume.</p>
    </body>
    </html>
