apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: busybox
        command: ["sh", "-c", "httpd -f -p 8080 -h /www && while true; do sleep 3600; done"]
        volumeMounts:
        - name: web-content
          mountPath: /www
        ports:
        - containerPort: 8080
      - name: sidecar
        image: busybox
        command: ["sh", "-c", "while true; do echo 'Sidecar logging info'; sleep 15; done"]
      volumes:
      - name: web-content
        configMap:
          name: web-content
